### ISSUE TITLE
Error when activating the plugin

### ISSUE THREAD

**Issue by m-muhsin** [royboy789/gutenberg-object-plugin#15]
I'm unable to activate the plugin. I get the following error:
Fatal error: Uncaught Error: Class 'ReactQuiz\QuizCPT' not found in C:\xampp\htdocs\react-gutenberg\wp-content\plugins\gutenberg-react-quiz-master\ReactQuizPlugin.php on line 138

**Comment by royboy789** [comment]
@m-muhsin are you using the release zip or the master branch?

If so you will need to run `composer install` to get the `vendor/` dir
