### ISSUE TITLE
Cannot edit Gutenberg content after enabling plugin

### ISSUE THREAD

**Issue by SimonIMG** [royboy789/gutenberg-object-plugin#17]
I tried installing both the composer version and the ZIP version.

As soon as I enable the plugin, I go to edit a Gutenberg post (add a heading, text or image) and when I click the Update button, I get...
```
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at CoreHeading.hookCallback (gutenberg-db.build.js?ver=1:3823)
    at Object.<anonymous> (index.js?ver=1535603880:1)
    at Function.cleanData (gutenberg-db.build.js?ver=1:1365)
    at SaveBlock.saveCallback (gutenberg-db.build.js?ver=1:1323)
    at index.js?ver=1535603880:1
    at Array.forEach (<anonymous>)
    at index.js?ver=1535603880:1
    at Object.d [as dispatch] (index.js?ver=1535603880:1)
    at dispatch (<anonymous>:1:38223)
    at lodash.min.59550321.js:49
```

**Comment by SimonIMG** [comment]
Steps to reproduce:
1. Install fresh version of WP and enable Gutenberg
2. Create a new Gutenberg post
3. Install gutenberg-object-plugin (clone, composer, npm install and run dev, activate)
4. Go back to edit the post (add a new block)
5. Click Update and check browser console

**Comment by royboy789** [comment]
Hi @SimonIMG  - sorry i didn't catch this earlier. Probably because Gutenberg keeps updating, I'll look at this over and create a fix..

THANK YOU

**Comment by brightidea** [comment]
While certainly not a long term fix (i don't have deep enough gutenberg knowledge to know if this will break something else) here is a short term solution I used this morning to get the plugin working until Roy releases a proper fix.

In the plugin folder run 'npm run dev' and then open assets >> js >> save-filters >> core-heading.js

change line 11 in that file from: 
`    
attributes.heading = attributes.nodeName.toLowerCase();
`
to:
`    
attributes.heading = attributes.nodeName !== undefined ? attributes.nodeName.toLowerCase() : ''
`

verify working then run 'npm run build'.

**Comment by royboy789** [comment]
Thank You @brightidea - 

ya definitely an issue with that block! Always fun coding for a moving target... fix is on master.

Thanks @SimonIMG  for finding this one
