### ISSUE TITLE
Different structure of output in previews/revisions

### ISSUE THREAD

**Issue by jhalvorson** [royboy789/gutenberg-object-plugin#19]
Hi,

This plugin has been a massive help. One thing I've noticed is that when viewing the output of a preview it is different to that of a standard post:

**Preview**
```
{
  "editor_blocks": [
    {
      "attrs": {...},
      "blockName": "core/paragraph",
      "innerBlocks": [],
      "innerHTML": "<p>just an example</p>"
    }
  ]
}
```
**Standard**
```
{
  "editor_blocks": [
    {
      "name": "core/paragraph",
      "data": {
        "content": "This is a test",
        "dropCap": false
      }
    }
  ]
}
```

I've taken a stab at it but I can't seem to get it to work, do you have any pointers?

I'm running the latest version from the master branch, WP 4.9.8 and Gutenberg 4.1.1.

Thanks!

**Comment by royboy789** [comment]
Sorry just getting back to working after being on leave.. will take a look..

thanks @jhalvorson

**Comment by royboy789** [comment]
Hi @jhalvorson  - looked at this, and haven't spent much time on revisions, I'll have to look at revision more closely. going to add this as a new feature request for a future version.

**Comment by royboy789** [comment]
So looking back at my code, the main reason the data differs is how its stored (or lack thereof). Revisions aren't stored in the new custom table, instead I pull revisions on the fly when making he API request here:
https://github.com/royboy789/gutenberg-object-plugin/blob/master/src/API.php#L249

The output you see is `gutenberg_parse_blocks` which is the default function built into Gutenberg. So maybe the "better" option here is to make the regular post data look like that, although I'm not fond of how it outputs, especially when it comes to HTML

Second option is to save revisions as I do posts in the custom table, but that seems like it will get excessively large, quickly.. so maybe just the latest revision? I have to think about that.

@jhalvorson what is your use case?
