### ISSUE TITLE
Save data back to Gutenberg when saving object

### ISSUE THREAD

**Issue by royboy789** [royboy789/gutenberg-object-plugin#2]
Suggestion from Kevin H. 
* When object data in DB is saved, that should sync with the normal / default Gutenberg data
* The data should sync both ways

**Comment by royboy789** [comment]
The problem with this idea, is that when the data object saves, should there be a `sync` option in Gutenberg which would override what is there. The issue being that when 2 points can save the same data 1 must have permissions over the others, unless there is a merge / sync option. 

I'm now thinking while a good idea, it might be better to make the assumption Gutenberg Editor is the only interface allowed to save data, and this plugin is just for reading data.

**Comment by kevinwhoffman** [comment]
@royboy789 I was thinking one of the major use cases for the plugin would be for sites using headless WordPress where structured data really shows its value. But if you can only read and not write the structured data, I think that would limit many use cases where content is being submitted on the front end.

**Comment by royboy789** [comment]
@kevinwhoffman - I agree it could be useful, but I'm worried about having multiple points that save the same data. How would you overcome both a headless app saving Gutes data and Gutes itself via WP admin?

**Comment by kevinwhoffman** [comment]
Seems like you would need a parser to convert the structured data back into blocks when the Gutenberg editor loads so you could handle the following scenario:

1. Author enters content in Gutenberg and publishes post.
2. Post content is altered via API.
3. Author revisits post in Gutenberg. At this point the structured data is parsed and rendered into blocks so the author sees the most up-to-date version of the data that is in sync with the structured data.
4. Author edits post in Gutenberg.
5. Content is saved to `post_content` _and_ as structured data so they remain in sync.

Honestly the two possible sources of truth (`post_content` and structured data) seems like it is destined for conflict. Perhaps it would be better to put all of your eggs in the structured data basket so content is only stored in one location that can be read from and written to. (I realize you lose backwards compatibility at that point and are locked into the plugin).

**Comment by royboy789** [comment]
@kevinwhoffman I agree - but I think we're talking about different things.

For the most part data goes from Gutenberg -> parsed -> DB so its `the_content()` what my plugin does is make a fork in the road so it goes Gutenberg -> new DB table, but the data still gets parsed and goes to the `wp_posts` table to keep backwards compatibility.

What your request was (that I understood) is that the data I'm storing (in a new table) should be modify-able, and that data should go back to Gutenberg editor.

Sync issue comes up when app has changed data, and then an editor loads up the page, or maybe had the editor open, how does the Gutes editor sync with the new data, or does it always override all.

**Comment by royboy789** [comment]
Closing this - I don't plan to have this plugin save data. I want Gutenberg editor to be the only truth when it comes to data. This plugin should only GET / READ not write.
