### ISSUE TITLE
Not getting all the content for blocks

### ISSUE THREAD

**Issue by botoxparty** [royboy789/gutenberg-object-plugin#22]
Hey,

Love this project, honestly can't believe it wasn't built into gutenberg from the beginning.

I seem to be having a problem where I dont get all the content for a block, e.g. for a media/text block I only get the media, not the text. I haven't tested all the blocks yet but yeah is this expected behaviour?

**Comment by royboy789** [comment]
@botoxparty I'll take a look, just getting back from leave. it may be a new block, or the block may not have all the default attributes.. I'll have to check my filters. Will close when I have it resolved. 

Which version of Gutenberg & WP are you running?

**Comment by botoxparty** [comment]
I'm using the latest of both on a fresh install.

Cool would also love to see how I could add attributes for custom blocks I
make.

**Comment by braco** [comment]
@royboy789 is this still a problem?

**Comment by royboy789** [comment]
Hi @botoxparty & @braco - I have merged `1.5.0` into master via PR #25 - can you pull latest master and try again? All seems to be working fine for me.

**Comment by royboy789** [comment]
@botoxparty by default any attributes for a block will appear under "data", if you want to add something custom, you can create a filter for it I have some documentation on how to do that in the  [README](https://github.com/royboy789/gutenberg-object-plugin#hooks)
