### ISSUE TITLE
[Request for documentation] example output

### ISSUE THREAD

**Issue by braco** [royboy789/gutenberg-object-plugin#23]
Hi, it would be helpful to see example output in the documentation.

Trying to determine if I can render an entire Gatsby site using the plugin.

**Comment by royboy789** [comment]
@braco - I too have tried to use this plugin to work on a Gatsby project. I could never get Gatsby to just work even with default WP output. Do you have an open repo somewhere? I would love to collab.

**Comment by royboy789** [comment]
@braco , good call on better documentation, let me get the Wiki going on this repo so I can create pages for that, would be nice to have a doc page for every block and what the plugin does with the data.

**Comment by royboy789** [comment]
Documentation Started:
https://github.com/royboy789/gutenberg-object-plugin/wiki

**Comment by braco** [comment]
> @braco - I too have tried to use this plugin to work on a Gatsby project. I could never get Gatsby to just work even with default WP output. Do you have an open repo somewhere? I would love to collab.

I don't have a public repo, but I would love to create one after I wrap things up internally.

Did you see this?:
https://www.gatsbyjs.org/packages/gatsby-source-wordpress/

IIRC there was a small key name bug in some of the GraphQL example queries.

**Comment by geocine** [comment]
@royboy789  @braco  I also ran into this issue this week. Here are my insights.

You need to create your own `gatsby-source-*` specifically for this plugin . Create a custom `gatsby-node.js` on your root gatsby project directory
```js
const axios = require("axios");
const crypto = require("crypto");

exports.sourceNodes = async (
  { actions, createNodeId, createContentDigest },
  configOptions
) => {
  const { createNode } = actions;

  // Gatsby adds a configOption that's not needed for this plugin, delete it
  delete configOptions.plugins;
  // Helper function that processes a post to match Gatsby's node structure
  const processPost = post => {
    const nodeId = createNodeId(`gutenberg-post-${post.post_id}`);
    const nodeContent = JSON.stringify(post);
    const nodeData = Object.assign({}, post, {
      id: nodeId,
      parent: null,
      children: [],
      internal: {
        type: `GutenbergPost`,
        content: nodeContent,
        contentDigest: crypto
          .createHash("md5")
          .update(JSON.stringify(post))
          .digest("hex")
      }
    });
    return nodeData;
  };

  // Gatsby expects sourceNodes to return a promise
  const pages = await axios.get(
    `http://localhost:8080/wp-json/wp/v2/pages?per_page=20`
  );

  return Promise.all(
    pages.data.map(({ id }) => {
      return axios
        .get(`http://localhost:8080/wp-json/gutes-db/v1/${id}`)
        .then(res => {
          res.data.data = res.data.data == false ? [] : res.data.data;
          const nodeData = processPost(res.data);
          createNode(nodeData);
        })
        .catch(err => err);
    })
  );
};

```
Notice that I am getting all the pages and querying it one by one using this plugin. I only chose a page size of 20 so its up to you . With this in place , you will be able to query data from graphql. 

```
{
  allGutenbergPost {
    edges {
      node {
        id: post_id
        is_gutes
	  data {
          name
          data {
            content
          }
        }
      }
    }
  }
}
```
I hope this helps
