### ISSUE TITLE
[Request] Add WP-rendered content

### ISSUE THREAD

**Issue by braco** [royboy789/gutenberg-object-plugin#24]
It seems important to get the rendered content in addition to the block data:

```
{
  name: "core/paragraph",
  data: ...,
  content: ...,
  dropcap: ...,
  rendered: '<html>'
}
```

This would allow for custom rendered blocks and WYSIWYG content to be mixed together.

**Comment by royboy789** [comment]
@braco  are you noticing with `core/paragraph` that the content isn't rendered? Its rendered by default.

```
{
    "name": "core/paragraph",
    "data": {
        "content": "The <strong>goal</strong> of this new editor is to make adding rich content to WordPress simple and enjoyable. This whole post is composed of <em>pieces of content</em>—somewhat similar to LEGO bricks—that you can move around and interact with. Move your cursor around and you’ll notice the different blocks light up with outlines and arrows. Press the arrows to reposition blocks quickly, without fearing about losing things in the process of copying and pasting.",
        "dropCap": false
    }
},
```

**Comment by braco** [comment]
I chose a poor example and was thinking more about things like tables and other more complicated structures.

The goal would be

```
foreach block
    if this is referring to a react module, use data and render through react
    else dump HTML from WP as-is
```

My personal goal is to get Gatsby rendering/building wherever possible instead of WP.

**Comment by royboy789** [comment]
@braco I think that depends on the block. I'm only supporting core blocks right now (and some WDS). I don't think the plugin should filter through the content to find things like tables, and then break it out into an easier to parse object. If a new block comes in and stores the data that way in the data attributes, that would be a different story and the plugin should work fine. 

If you can think of a good core block example, let me know and I will re-open
