### ISSUE TITLE
ACF Field names 

### ISSUE THREAD

**Issue by mortennh** [royboy789/gutenberg-object-plugin#32]
Is there a way to output the correct field names of ACF generated blocks?

Example:

```json
{
    "clientId": "689c35b4-7e5c-40be-9bbc-62567d2f52fd",
    "name": "acf/persona-data",
    "isValid": true,
    "originalContent": "",
    "attributes": {
        "id": "block_5c765be24819b",
        "data": {
            "field_5c76577121aa0": {
                "5c765be34819c": {
                    "field_5c75805f71339": "2016",
                    "field_5c7580697133a": "text"
                },
                "5c765c27e768c": {
                    "field_5c75805f71339": "2017",
                    "field_5c7580697133a": "test"
                },
                "5c765c2ee768d": {
                    "field_5c75805f71339": "2016",
                    "field_5c7580697133a": "test"
                }
            }
        },
        "name": "acf/persona-data",
        "align": "",
        "mode": "preview",
        "bid": "1fe0d"
    },
    "innerBlocks": []
}
```

I'm expecting the data to be formatted as:

```json
"data": {
    "persona_data": {
        "year": "2016",
        "description": "text"
    }
}
```

Got any ideas?

**Comment by royboy789** [comment]
hi @mortensassi sorry just saw this.. did you fix this? I think something like this would need to be handled specifically per block or at least per field. I wonder if there is something I could tie into ACF for to always grab the right field data based on field ID. 

When I get a chance I"ll look into this. Are you using custom blocks or ACF 5.8+ generated blocks?

**Comment by mortennh** [comment]
Hey @royboy789, 

thank you for reaching out! Since the issue is some days old, i need to take a look at the object again. but this is the current working stack:

WP: 5.2.3 
ACF Pro: 5.8.2

I was wondering why you didn't take the already defined `field_name` ? I can ask a backend-dev if he can take a look at your code, too and come back

**Comment by mattpilott** [comment]
Hey @royboy789 this would be a great addition, i need this atm
