### ISSUE TITLE
Packagist‽

### ISSUE THREAD

**Issue by thefrosty** [royboy789/gutenberg-object-plugin#36]
Why haven't you registered this plugin with Packagist‽ (╯°□°)╯︵ ┻━┻

**Comment by thomasxbanks** [comment]
https://packagist.org/packages/wp-kit/gutenberg-object-plugin
🙂

**Comment by royboy789** [comment]
I'll accept it. Thanks @thomasxbanks

**Comment by thefrosty** [comment]
@thomasxbanks did you get this setup so that it auto-updates on release tags, or is it contingent on your forked copy being updated?

**Comment by davidohlin** [comment]
not sure what's going on in the wp-kit fork, but the type field has been removed from `composer.json` in [(this commit)](
https://github.com/wp-kit/gutenberg-object-plugin/commit/ea34b9f10e5b55dbe406ab49f32ca2e5f4a9c5f5), so I'm not able to install it anyway. It also doesn't seem to auto-update, to answer @thefrosty.

**Comment by thefrosty** [comment]
Which is why I thumbs downed that reply @davidohlin. Composer packagist should be the actual resource, not a fork.
