### ISSUE TITLE
Does this work on multi sites?

### ISSUE THREAD

**Issue by anim8rDev** [royboy789/gutenberg-object-plugin#39]
I tried to Network Activate this plugin and it threw an error.  Is this not compatible with Multi Sites?

Thank you

Plugin could not be activated because it triggered a fatal error.

Fatal error: Uncaught Error: Class 'GutesObjectPlugin\Scripts' not found in /home/.../wp-content/plugins/gutenberg-object-plugin-2.0.0/GutesObjectPlugin.php:52 Stack trace: #0 /home/.../wp-admin/includes/plugin.php(2141): include() #1 /home/.../wp-admin/plugins.php(175): plugin_sandbox_scrape('gutenberg-objec...') #2 {main} thrown in /home/.../wp-content/plugins/gutenberg-object-plugin-2.0.0/GutesObjectPlugin.php on line 52

**Comment by anim8rDev** [comment]
I tried installing this on a second non-multisite WP installation and had the same error.  Any ideas?

**Comment by pftiller** [comment]
Same issue

**Comment by p11v** [comment]
+1

**Comment by royboy789** [comment]
@pdxDev, @pftiller, @plamenh - thanks for calling this out.. I never played around with it on a multisite! I'll try to remember to test it out and fix the issue ASAP. 

Did you run through all the install instructions? The error you're pointing out looks like a class not found error, which leads me to believe you didn't run `composer install`. 

If you don't have composer and npm, I can create a built version which should be more plug and play.
