### ISSUE TITLE
Updating from Wordpress IOS app does not work

### ISSUE THREAD

**Issue by tcober** [royboy789/gutenberg-object-plugin#40]
If I make a change in the Wordpress ios app, the changes are reflected in the generic Gutenberg "content" block but are not reflected in your snazzy new 'editor_blocks'. If I save from the web app it does update correctly though.

**Comment by royboy789** [comment]
@tcober this is an interesting issue. I wonder why. Maybe the iOS app doesn't run the same data changes, the whole thing is triggered by a `data.subscribe` here:
https://github.com/royboy789/gutenberg-object-plugin/blob/master/assets/js/block-save/block-save.js#L5

I'll have to play with this more later. but good to know!
