### ISSUE TITLE
composer.json issues

### ISSUE THREAD

**Issue by tomjn** [royboy789/gutenberg-object-plugin#8]
- PHP 5.3 is required, possibly 5.4 but nothing is mentioned in the requirements section
 - The package type is `project` not `wordpress-plugin` and the composer installers package is missing from the requirements. Installing via a standard WP composer setup is not possible

**Comment by royboy789** [comment]
@tomjn I don't use composer too much to bring in other projects, check out #13 file changes and see if that works.. thanks!

**Comment by tomjn** [comment]
Looks good
